"""Reusable electrical-equivalence primitives.

This module is deliberately independent of corpus-evaluation orchestration so
production schematic refinement and offline corpus evaluation share the same
electrical comparison implementation.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Iterable
from dataclasses import asdict, dataclass, field as dataclass_field

from .circuit_ir import CircuitIR, ComponentIR, NetIR

_UNNAMED_NET_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^Net-\(.+\)$"),
    re.compile(r"^unconnected-\(.+\)$"),
)


@dataclass(frozen=True, order=True)
class ElectricalTerminal:
    """Canonical logical terminal identity."""

    ref: str
    pin: str
    unit: str = ""


@dataclass(frozen=True, order=True)
class ElectricalComponentFingerprint:
    """Immutable logical component identity used by electrical fingerprints."""

    ref: str
    symbol: str
    value: str
    footprint: str
    units: tuple[str, ...] = ()


@dataclass(frozen=True, order=True)
class ElectricalNamedNetFingerprint:
    """One named net and its exact terminal membership."""

    name: str
    terminals: tuple[ElectricalTerminal, ...]


@dataclass(frozen=True)
class SchematicElectricalFingerprint:
    """Versioned, deterministic electrical fingerprint.

    Presentation geometry is intentionally absent. ``no_connect_terminals`` is
    populated only when the caller has schematic-level evidence for explicit
    intentional no-connect markers.
    """

    schema_version: str
    components: tuple[ElectricalComponentFingerprint, ...]
    named_nets: tuple[ElectricalNamedNetFingerprint, ...]
    unnamed_net_partitions: tuple[tuple[ElectricalTerminal, ...], ...]
    no_connect_terminals: tuple[ElectricalTerminal, ...] = ()

    def canonical_payload(self) -> dict[str, object]:
        return asdict(self)

    def sha256(self) -> str:
        payload = json.dumps(
            self.canonical_payload(),
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        return hashlib.sha256(payload).hexdigest()


@dataclass(frozen=True)
class ElectricalMismatch:
    """One deterministic electrical mismatch."""

    field: str
    expected: str
    actual: str
    code: str = "ELECTRICAL_MISMATCH"
    component_ref: str | None = None
    net_name: str | None = None
    pin: str | None = None
    details: dict[str, object] = dataclass_field(default_factory=dict)


@dataclass(frozen=True)
class ElectricalEquivalenceReport:
    """Hard pass/fail report for electrical equivalence."""

    status: str
    mismatches: tuple[ElectricalMismatch, ...] = dataclass_field(default_factory=tuple)


def is_generated_unnamed_net_name(name: str) -> bool:
    """Return true only for narrowly recognized KiCad autogenerated net names."""

    return any(pattern.fullmatch(name) is not None for pattern in _UNNAMED_NET_PATTERNS)


def terminal_from_pin(pin: object) -> ElectricalTerminal:
    """Build a terminal from a PinRefIR-like object."""

    ref = getattr(pin, "ref")
    number = getattr(pin, "pin")
    unit = getattr(pin, "unit", None) or ""
    return ElectricalTerminal(ref=str(ref), pin=str(number), unit=str(unit))


def build_circuit_ir_fingerprint(
    ir: CircuitIR,
    *,
    no_connect_terminals: Iterable[ElectricalTerminal] = (),
) -> SchematicElectricalFingerprint:
    """Build a canonical fingerprint from Circuit IR plus optional NC evidence."""

    normalized = canonicalize_for_electrical_comparison(ir)
    units_by_ref: dict[str, set[str]] = {}
    for net in normalized.nets:
        for pin in net.pins:
            if pin.unit:
                units_by_ref.setdefault(pin.ref, set()).add(pin.unit)

    components = tuple(
        ElectricalComponentFingerprint(
            ref=component.ref,
            symbol=component.symbol,
            value=component.value or "",
            footprint=component.footprint or "",
            units=tuple(sorted(units_by_ref.get(component.ref, set()))),
        )
        for component in normalized.components
    )

    named_nets: list[ElectricalNamedNetFingerprint] = []
    unnamed_partitions: list[tuple[ElectricalTerminal, ...]] = []
    for net in normalized.nets:
        terminals = tuple(sorted(terminal_from_pin(pin) for pin in net.pins))
        if is_generated_unnamed_net_name(net.name):
            unnamed_partitions.append(terminals)
        else:
            named_nets.append(ElectricalNamedNetFingerprint(name=net.name, terminals=terminals))

    return SchematicElectricalFingerprint(
        schema_version="1.0",
        components=components,
        named_nets=tuple(sorted(named_nets)),
        unnamed_net_partitions=tuple(sorted(unnamed_partitions)),
        no_connect_terminals=tuple(sorted(set(no_connect_terminals))),
    )


def compare_circuit_ir_equivalence(
    source: CircuitIR,
    generated: CircuitIR,
    *,
    compare_footprints: bool = False,
) -> ElectricalEquivalenceReport:
    """Return a hard pass/fail electrical equivalence report.

    Named nets preserve identity. Narrowly-recognized KiCad autogenerated net
    names compare by connected-terminal partition so harmless autogenerated
    renames do not fail equivalence.
    """

    source_ir = canonicalize_for_electrical_comparison(source)
    generated_ir = canonicalize_for_electrical_comparison(
        normalize_multi_unit_generated_refs(source_ir, generated)
    )
    mismatches: list[ElectricalMismatch] = []

    source_components = {component.ref: component for component in source_ir.components}
    generated_components = {component.ref: component for component in generated_ir.components}
    if source_components.keys() != generated_components.keys():
        mismatches.append(
            ElectricalMismatch(
                code="COMPONENT_REFS_MISMATCH",
                field="component_refs",
                expected=",".join(sorted(source_components)),
                actual=",".join(sorted(generated_components)),
                details={
                    "missing_refs": sorted(source_components.keys() - generated_components.keys()),
                    "extra_refs": sorted(generated_components.keys() - source_components.keys()),
                },
            )
        )

    for ref in sorted(source_components.keys() & generated_components.keys()):
        expected_component = source_components[ref]
        actual_component = generated_components[ref]
        if (expected_component.value or "") != (actual_component.value or ""):
            mismatches.append(
                ElectricalMismatch(
                    code="COMPONENT_VALUE_MISMATCH",
                    field=f"component_value:{ref}",
                    expected=expected_component.value or "",
                    actual=actual_component.value or "",
                    component_ref=ref,
                )
            )
        if expected_component.symbol != actual_component.symbol:
            mismatches.append(
                ElectricalMismatch(
                    code="COMPONENT_SYMBOL_MISMATCH",
                    field=f"component_symbol:{ref}",
                    expected=expected_component.symbol,
                    actual=actual_component.symbol,
                    component_ref=ref,
                )
            )
        if compare_footprints and (expected_component.footprint or "") != (
            actual_component.footprint or ""
        ):
            mismatches.append(
                ElectricalMismatch(
                    code="COMPONENT_FOOTPRINT_MISMATCH",
                    field=f"component_footprint:{ref}",
                    expected=expected_component.footprint or "",
                    actual=actual_component.footprint or "",
                    component_ref=ref,
                )
            )

    source_named, source_unnamed = _partition_nets(source_ir)
    generated_named, generated_unnamed = _partition_nets(generated_ir)
    if source_named.keys() != generated_named.keys():
        mismatches.append(
            ElectricalMismatch(
                code="NET_NAMES_MISMATCH",
                field="net_names",
                expected=",".join(sorted(source_named)),
                actual=",".join(sorted(generated_named)),
                details={
                    "missing_names": sorted(source_named.keys() - generated_named.keys()),
                    "extra_names": sorted(generated_named.keys() - source_named.keys()),
                },
            )
        )
    for name in sorted(source_named.keys() & generated_named.keys()):
        if source_named[name] != generated_named[name]:
            mismatches.append(
                ElectricalMismatch(
                    code="NET_TERMINALS_MISMATCH",
                    field=f"net_pins:{name}",
                    expected=str(list(source_named[name])),
                    actual=str(list(generated_named[name])),
                    net_name=name,
                )
            )

    if source_unnamed != generated_unnamed:
        mismatches.append(
            ElectricalMismatch(
                code="UNNAMED_NET_PARTITIONS_MISMATCH",
                field="unnamed_net_partitions",
                expected=str(source_unnamed),
                actual=str(generated_unnamed),
            )
        )

    ordered = tuple(sorted(mismatches, key=lambda item: (item.field, item.code)))
    return ElectricalEquivalenceReport(
        status="passed" if not ordered else "failed",
        mismatches=ordered,
    )


def canonicalize_for_electrical_comparison(ir: CircuitIR) -> CircuitIR:
    """Normalize safe sheet-scoped names and sort all electrical members."""

    return _canonicalize_circuit_ir(_normalize_sheet_scoped_net_names(ir))


def normalize_multi_unit_generated_refs(source: CircuitIR, generated: CircuitIR) -> CircuitIR:
    """Collapse proven generated split refs such as ``U1A`` to logical refs.

    The alias is only permitted when the base ref exists in the authoritative
    source and unit evidence/group cardinality proves a multi-unit expansion.
    """

    source_refs = {component.ref for component in source.components}
    source_units_by_ref = _units_by_ref(source)
    generated_units_by_ref = _units_by_ref(generated)

    base_group_counts: dict[str, int] = {}
    for component in generated.components:
        base_ref = _logical_multi_unit_base_ref(component.ref, source_refs)
        if base_ref is not None:
            base_group_counts[base_ref] = base_group_counts.get(base_ref, 0) + 1

    alias_map = {
        component.ref: _canonical_generated_ref(
            component.ref,
            source_refs=source_refs,
            source_units_by_ref=source_units_by_ref,
            generated_units_by_ref=generated_units_by_ref,
            base_group_counts=base_group_counts,
        )
        for component in generated.components
    }

    components_by_ref: dict[str, ComponentIR] = {}
    for component in generated.components:
        canonical_ref = alias_map[component.ref]
        candidate = component.model_copy(update={"ref": canonical_ref}, deep=True)
        existing = components_by_ref.get(canonical_ref)
        if existing is None:
            components_by_ref[canonical_ref] = candidate
            continue
        if (
            existing.symbol != candidate.symbol
            or (existing.value or "") != (candidate.value or "")
            or (existing.footprint or "") != (candidate.footprint or "")
        ):
            components_by_ref[component.ref] = component.model_copy(deep=True)

    nets = [
        NetIR(
            name=net.name,
            pins=[
                pin.model_copy(update={"ref": alias_map.get(pin.ref, pin.ref)}, deep=True)
                for pin in net.pins
            ],
        )
        for net in generated.nets
    ]
    return CircuitIR(
        version=generated.version,
        components=list(components_by_ref.values()),
        nets=nets,
        options=generated.options,
    )


def _partition_nets(
    ir: CircuitIR,
) -> tuple[
    dict[str, tuple[tuple[str, str, str], ...]],
    tuple[tuple[tuple[str, str, str], ...], ...],
]:
    named: dict[str, tuple[tuple[str, str, str], ...]] = {}
    unnamed: list[tuple[tuple[str, str, str], ...]] = []
    for net in ir.nets:
        terminals = tuple(sorted((pin.ref, pin.pin, pin.unit or "") for pin in net.pins))
        if is_generated_unnamed_net_name(net.name):
            unnamed.append(terminals)
        else:
            named[net.name] = terminals
    return named, tuple(sorted(unnamed))


def _canonicalize_circuit_ir(ir: CircuitIR) -> CircuitIR:
    components = sorted(ir.components, key=lambda component: component.ref)
    nets = [
        NetIR(
            name=net.name,
            pins=sorted(net.pins, key=lambda pin: (pin.ref, pin.pin, pin.unit or "")),
        )
        for net in sorted(ir.nets, key=lambda net: net.name)
    ]
    return CircuitIR(version=ir.version, components=components, nets=nets, options=ir.options)


def _normalize_sheet_scoped_net_names(ir: CircuitIR) -> CircuitIR:
    candidate_names = {net.name: _sheet_scoped_tail(net.name) for net in ir.nets}
    candidate_pins: dict[str, set[tuple[tuple[str, str, str], ...]]] = {}
    for net in ir.nets:
        pin_key = tuple(sorted((pin.ref, pin.pin, pin.unit or "") for pin in net.pins))
        candidate_pins.setdefault(candidate_names[net.name], set()).add(pin_key)

    normalized_nets: list[NetIR] = []
    seen_names: dict[str, tuple[tuple[str, str, str], ...]] = {}
    for net in ir.nets:
        pin_key = tuple(sorted((pin.ref, pin.pin, pin.unit or "") for pin in net.pins))
        candidate_name = candidate_names[net.name]
        normalized_name = net.name
        if candidate_name != net.name and len(candidate_pins[candidate_name]) == 1:
            normalized_name = candidate_name
        existing_pin_key = seen_names.get(normalized_name)
        if existing_pin_key == pin_key:
            continue
        normalized_nets.append(NetIR(name=normalized_name, pins=net.pins))
        seen_names[normalized_name] = pin_key

    return CircuitIR(
        version=ir.version,
        components=ir.components,
        nets=normalized_nets,
        options=ir.options,
    )


def _units_by_ref(ir: CircuitIR) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for net in ir.nets:
        for pin in net.pins:
            if pin.unit:
                result.setdefault(pin.ref, set()).add(pin.unit)
    return result


def _canonical_generated_ref(
    ref: str,
    *,
    source_refs: set[str],
    source_units_by_ref: dict[str, set[str]],
    generated_units_by_ref: dict[str, set[str]],
    base_group_counts: dict[str, int],
) -> str:
    if ref in source_refs:
        return ref
    base_ref = _logical_multi_unit_base_ref(ref, source_refs)
    if base_ref is None:
        return ref

    generated_units = generated_units_by_ref.get(ref, set())
    source_units = source_units_by_ref.get(base_ref, set())
    if generated_units and source_units and not generated_units <= source_units:
        return ref
    if generated_units or base_group_counts.get(base_ref, 0) > 1:
        return base_ref
    return ref


def _logical_multi_unit_base_ref(ref: str, source_refs: set[str]) -> str | None:
    if len(ref) < 2 or not ref[-1].isalpha():
        return None
    base_ref = ref[:-1]
    return base_ref if base_ref in source_refs else None


def _sheet_scoped_tail(net_name: str) -> str:
    if not net_name.startswith("/"):
        return net_name
    tail = net_name.rsplit("/", 1)[-1].strip()
    return tail or net_name
