"""Orthogonal net routing for kicad_pcb managed schematics.

Routes 2-pin nets directly with L-shaped wire segments when both pins
are known and within :data:`MAX_DIRECT_DIST_MM` (Manhattan distance,
stub-end to stub-end).  For nets with 3–:data:`_HUB_MAX_DEGREE` pins the
default strategy is spine routing (bus-style wire with T-junction taps),
which produces cleaner schematics than the per-pin stub+label fallback.
All other nets fall back to the classic wire-stub + net-label-per-pin
approach.

Public API
----------
:func:`route_nets`             — compute routing decisions for all nets in a CircuitIR.
:func:`write_routing`          — emit computed decisions into a SchematicDoc.
:class:`LabelPolicy`           — policy dataclass controlling label deduplication.
:data:`DEFAULT_LABEL_POLICY`   — default policy (max 2 local labels, 4 global per net).
:class:`PowerSymbolPlacement`  — placed power symbol (GND/VCC etc.), emitted for power nets.

Implementation note
-------------------
This module is a thin re-export wrapper around six focused sub-modules:

* ``_router_types``      — constants, data classes, LabelPolicy, RoutingHeuristicPolicy
* ``_router_classify``   — net classification, geometry helpers, label promotion
* ``_router_geometry``   — pin anchors, L-route, wire helpers, power geometry
* ``_router_write``      — wire simplification, clustering, write_routing
* ``_router_strategies`` — hub/spine/lane/chain/ladder routing strategies
* ``_router_route_nets`` — the main route_nets function
"""

from __future__ import annotations

# Re-export everything that external callers (tests, commands) depend on.
# The noqa: F401 comments suppress "imported but unused" warnings.
from ._router_classify import (  # noqa: F401
    _append_promoted_visible_label,
    _boxes_touch_or_overlap,
    _classification_prefers_compact_tail,
    _classification_prefers_local_chain,
    _classification_prefers_short_local_direct_route,
    _classify_routing_net,
    _cluster_power_pins,
    _compact_cluster_detour_x,
    _is_compact_horizontal_stage_tail,
    _is_compact_rightward_tail,
    _is_local_ladder_net,
    _is_power_net_name,
    _label_role_priority,
    _name_suggests_important_signal,
    _net_is_important_for_display,
    _net_member_roles,
    _point_in_or_on_box,
    _preferred_shared_lane,
    _prioritize_label_candidates,
    _roles_mark_important_display_seam,
    _should_promote_visible_label,
    _tier_distance,
    _VisibleLabelPromotion,
    _wire_crosses_box,
    detect_body_crossings,
)
from ._router_geometry import (  # noqa: F401
    _aligned_power_cluster_route_points,
    _append_direct_power_symbol,
    _append_pin_endpoint_labels,
    _best_direct_route_with_protected_points,
    _coerce_pin_anchor_map,
    _fallback_power_label_position,
    _foreign_attachment_points_for_known,
    _horizontal_first_l_route,
    _is_connector_passive_edge,
    _known_pin_stub_hits_foreign_attachment,
    _l_route,
    _l_route_with_protected_points,
    _label_attachment_plan,
    _manhattan,
    _occupied_label_points,
    _occupied_wire_points,
    _offset_point_along_angle,
    _point_on_segment,
    _power_cluster_angle,
    _power_label_angle_for_pin,
    _power_symbol_angle,
    _resolve_pin_anchors,
    _route_candidate_key,
    _route_protected_point_score,
    _safe_pin_label_anchor,
    _safe_stub_label_anchor,
    _segment_label_angle,
    _snap_grid,
    _stub_end,
    _three_segment_route_via_x,
    _three_segment_route_via_y,
    _vertical_first_l_route,
    _wire_path_length,
)
from ._router_route_nets import route_nets  # noqa: F401
from ._router_strategies import (  # noqa: F401
    _assign_connector_entry_grouped_lanes,
    _assign_grouped_ladder_lanes,
    _best_compact_vertical_tail_route,
    _buffer_follower_feedback_route,
    _build_ladder_adjacency,
    _chain_route,
    _choose_compact_ground_lane,
    _collect_local_ladder_candidates,
    _compact_aligned_chain_route,
    _compact_horizontal_stage_tail_route,
    _compact_local_decoupling_ground_cluster_route,
    _compact_local_decoupling_power_cluster_route,
    _compact_local_ground_cluster_route,
    _compact_vertical_tail_clearance_x,
    _compact_vertical_tail_members,
    _compact_vertical_tail_route,
    _compact_vertical_tail_tail_y,
    _connected_ladder_component,
    _decoupling_ground_members,
    _hub_route,
    _infer_bounded_local_lane_plan,
    _is_small_analog_chain_candidate,
    _lane_center,
    _plan_local_ladder_routes,
    _plan_single_grouped_ladder_lane,
    _prefer_chain_route,
    _prefer_small_analog_chain_route,
    _protected_shared_lane_route,
    _route_length,
    _route_visual_cost,
    _shared_lane_route,
    _should_skip_inferred_lane_plan,
    _spine_route,
)
from ._router_types import (  # noqa: F401
    _HUB_MAX_DEGREE,
    _POWER_CLUSTER_RADIUS_MM,
    _POWER_LABEL_CLEARANCE_MM,
    DEBUG_LABEL_POLICY,
    DEFAULT_LABEL_POLICY,
    DEFAULT_ROUTING_HEURISTIC_POLICY,
    IMPORTANT_LABEL_POLICY,
    LABEL_MODE_POLICIES,
    MAX_DIRECT_DIST_MM,
    MAX_DIRECT_WIRE_MM,
    MINIMAL_LABEL_POLICY,
    SYMBOL_HALF_SIZE_MM,
    WIRE_EXTEND_MM,
    BindMarker,
    GlobalLabelPlacement,
    JunctionPoint,
    LabelModeName,
    LabelPolicy,
    LadderLanePlannerContext,
    NetLabel,
    NetRouting,
    PinAnchor,
    PowerSymbolPlacement,
    RouteDecision,
    RoutingHeuristicPolicy,
    SharedLanePlan,
    WireSegment,
    _ProtectedPointContext,
)
from ._router_write import (  # noqa: F401
    _aligned_power_cluster_route_points as _aligned_power_cluster_route_points_write,
)
from ._router_write import (
    _clamp_emitted_power_symbols,
    _cluster_emitted_power_symbols,
    _infer_safe_t_junctions,
    _should_cluster_emitted_power_symbols,
    _simplify_wires,
    _split_wires_at_points,
    write_routing,
)

# Explicit re-export list — prevents ruff from removing backward-compat imports.
__all__ = [
    # _router_classify
    "_append_promoted_visible_label",
    "_boxes_touch_or_overlap",
    "_classification_prefers_compact_tail",
    "_classification_prefers_local_chain",
    "_classification_prefers_short_local_direct_route",
    "_classify_routing_net",
    "_cluster_power_pins",
    "_compact_cluster_detour_x",
    "_is_compact_horizontal_stage_tail",
    "_is_compact_rightward_tail",
    "_is_local_ladder_net",
    "_is_power_net_name",
    "_label_role_priority",
    "_name_suggests_important_signal",
    "_net_is_important_for_display",
    "_net_member_roles",
    "_point_in_or_on_box",
    "_preferred_shared_lane",
    "_prioritize_label_candidates",
    "_roles_mark_important_display_seam",
    "_should_promote_visible_label",
    "_tier_distance",
    "_VisibleLabelPromotion",
    "_wire_crosses_box",
    "detect_body_crossings",
    # _router_geometry
    "_aligned_power_cluster_route_points",
    "_append_direct_power_symbol",
    "_append_pin_endpoint_labels",
    "_best_direct_route_with_protected_points",
    "_coerce_pin_anchor_map",
    "_fallback_power_label_position",
    "_foreign_attachment_points_for_known",
    "_horizontal_first_l_route",
    "_is_connector_passive_edge",
    "_known_pin_stub_hits_foreign_attachment",
    "_l_route",
    "_l_route_with_protected_points",
    "_label_attachment_plan",
    "_manhattan",
    "_occupied_label_points",
    "_occupied_wire_points",
    "_offset_point_along_angle",
    "_point_on_segment",
    "_power_cluster_angle",
    "_power_label_angle_for_pin",
    "_power_symbol_angle",
    "_resolve_pin_anchors",
    "_route_candidate_key",
    "_route_protected_point_score",
    "_safe_pin_label_anchor",
    "_safe_stub_label_anchor",
    "_segment_label_angle",
    "_snap_grid",
    "_stub_end",
    "_three_segment_route_via_x",
    "_three_segment_route_via_y",
    "_vertical_first_l_route",
    "_wire_path_length",
    # _router_route_nets
    "route_nets",
    # _router_strategies
    "_assign_connector_entry_grouped_lanes",
    "_assign_grouped_ladder_lanes",
    "_best_compact_vertical_tail_route",
    "_buffer_follower_feedback_route",
    "_build_ladder_adjacency",
    "_chain_route",
    "_choose_compact_ground_lane",
    "_collect_local_ladder_candidates",
    "_compact_aligned_chain_route",
    "_compact_horizontal_stage_tail_route",
    "_compact_local_decoupling_ground_cluster_route",
    "_compact_local_decoupling_power_cluster_route",
    "_compact_local_ground_cluster_route",
    "_compact_vertical_tail_clearance_x",
    "_compact_vertical_tail_members",
    "_compact_vertical_tail_route",
    "_compact_vertical_tail_tail_y",
    "_connected_ladder_component",
    "_decoupling_ground_members",
    "_hub_route",
    "_infer_bounded_local_lane_plan",
    "_is_small_analog_chain_candidate",
    "_lane_center",
    "_plan_local_ladder_routes",
    "_plan_single_grouped_ladder_lane",
    "_prefer_chain_route",
    "_prefer_small_analog_chain_route",
    "_protected_shared_lane_route",
    "_route_length",
    "_route_visual_cost",
    "_shared_lane_route",
    "_should_skip_inferred_lane_plan",
    "_spine_route",
    # _router_types
    "_HUB_MAX_DEGREE",
    "_POWER_CLUSTER_RADIUS_MM",
    "_POWER_LABEL_CLEARANCE_MM",
    "_ProtectedPointContext",
    "WIRE_EXTEND_MM",
    "BindMarker",
    "DEBUG_LABEL_POLICY",
    "DEFAULT_LABEL_POLICY",
    "DEFAULT_ROUTING_HEURISTIC_POLICY",
    "GlobalLabelPlacement",
    "IMPORTANT_LABEL_POLICY",
    "JunctionPoint",
    "LABEL_MODE_POLICIES",
    "LabelModeName",
    "LabelPolicy",
    "LadderLanePlannerContext",
    "MAX_DIRECT_DIST_MM",
    "MAX_DIRECT_WIRE_MM",
    "MINIMAL_LABEL_POLICY",
    "NetLabel",
    "NetRouting",
    "PinAnchor",
    "PowerSymbolPlacement",
    "RouteDecision",
    "RoutingHeuristicPolicy",
    "SharedLanePlan",
    "SYMBOL_HALF_SIZE_MM",
    "WireSegment",
    # _router_write
    "_aligned_power_cluster_route_points_write",
    "_clamp_emitted_power_symbols",
    "_cluster_emitted_power_symbols",
    "_infer_safe_t_junctions",
    "_should_cluster_emitted_power_symbols",
    "_simplify_wires",
    "_split_wires_at_points",
    "write_routing",
]
