"""Parse native KiCad S-expression netlist topology."""

from __future__ import annotations

import re
from dataclasses import dataclass

from kicad_pcb.sexpr import AtomNode, ListNode, StringNode, parse

_AUTOGENERATED_NET_RE = re.compile(r"^Net-\(.+\)$")


@dataclass(frozen=True, order=True)
class KicadSexprNetPin:
    """One component pin referenced by a native KiCad netlist net."""

    ref: str
    pin: str


@dataclass(frozen=True)
class KicadSexprNet:
    """One native KiCad net and its exact terminal partition."""

    code: int
    name: str
    pins: tuple[KicadSexprNetPin, ...]
    autogenerated: bool


def parse_kicadsexpr_nets(content: str) -> tuple[KicadSexprNet, ...]:
    """Return net topology from a native ``kicadsexpr`` export.

    KiCad may serialize an unnamed net with an empty ``(name ...)`` field.
    Such nets receive a deterministic ``Net-(...)`` identity locally so the
    electrical-equivalence layer can reconcile them by exact topology. The
    synthesized name never changes or augments the terminal partition.
    """

    root = parse(content)
    if root.key != "export":
        raise ValueError(f"Expected KiCad netlist '(export ...)' root, got {root.key!r}")

    nets_node = _first_child(root, "nets")
    if nets_node is None:
        return ()

    parsed: list[KicadSexprNet] = []
    for node in nets_node.items[1:]:
        if not isinstance(node, ListNode) or node.key != "net":
            continue

        code_text = _child_scalar(node, "code")
        if code_text is None:
            raise ValueError("KiCad native net is missing its code")
        try:
            code = int(code_text)
        except ValueError as exc:
            raise ValueError(f"Invalid KiCad native net code: {code_text!r}") from exc
        if code <= 0:
            continue

        pins: list[KicadSexprNetPin] = []
        for child in node.items[1:]:
            if not isinstance(child, ListNode) or child.key != "node":
                continue
            ref = _child_scalar(child, "ref")
            pin = _child_scalar(child, "pin")
            if ref is None or pin is None:
                raise ValueError(f"KiCad native net {code} contains an incomplete node")
            pins.append(KicadSexprNetPin(ref=ref, pin=pin))

        if not pins:
            continue

        pins_tuple = tuple(sorted(set(pins)))
        raw_name = (_child_scalar(node, "name") or "").strip()
        autogenerated = not raw_name or _AUTOGENERATED_NET_RE.fullmatch(raw_name) is not None
        name = raw_name or _synthetic_autogenerated_name(pins_tuple)
        parsed.append(
            KicadSexprNet(
                code=code,
                name=name,
                pins=pins_tuple,
                autogenerated=autogenerated,
            )
        )

    return tuple(sorted(parsed, key=lambda net: (net.code, net.name, net.pins)))


def _first_child(node: ListNode, key: str) -> ListNode | None:
    return next(
        (
            child
            for child in node.items[1:]
            if isinstance(child, ListNode) and child.key == key
        ),
        None,
    )


def _child_scalar(node: ListNode, key: str) -> str | None:
    child = _first_child(node, key)
    if child is None or len(child.items) < 2:
        return None
    value = child.items[1]
    if isinstance(value, (AtomNode, StringNode)):
        return value.value
    return None


def _synthetic_autogenerated_name(pins: tuple[KicadSexprNetPin, ...]) -> str:
    first = pins[0]
    return f"Net-({first.ref}-Pad{first.pin})"
