from __future__ import annotations

from kicad_pcb.circuit_ir import CircuitIR
from kicad_pcb.electrical_equivalence import compare_circuit_ir_equivalence


def _ir(*, nets: list[dict[str, object]], refs: tuple[str, ...] = ("R1", "R2")) -> CircuitIR:
    return CircuitIR.model_validate(
        {
            "version": "1",
            "components": [
                {"ref": ref, "symbol": "Device:R", "value": "1k"} for ref in refs
            ],
            "nets": nets,
        }
    )


def _pins(*pins: tuple[str, str]) -> list[dict[str, str]]:
    return [{"ref": ref, "pin": pin} for ref, pin in pins]


def test_named_net_matches_unique_kicad_autogenerated_net_by_exact_topology() -> None:
    source = _ir(nets=[{"name": "VMID", "pins": _pins(("R1", "2"), ("R2", "1"))}])
    generated = _ir(
        nets=[{"name": "Net-(R1-Pad2)", "pins": _pins(("R1", "2"), ("R2", "1"))}]
    )

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "passed"
    assert report.mismatches == ()


def test_named_net_does_not_match_autogenerated_net_with_changed_topology() -> None:
    source = _ir(nets=[{"name": "VMID", "pins": _pins(("R1", "2"), ("R2", "1"))}])
    generated = _ir(nets=[{"name": "Net-(R1-Pad2)", "pins": _pins(("R1", "2"))}])

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "failed"
    assert {mismatch.code for mismatch in report.mismatches} >= {
        "NET_NAMES_MISMATCH",
        "UNNAMED_NET_PARTITIONS_MISMATCH",
    }


def test_named_net_does_not_match_explicit_wrong_name_with_same_topology() -> None:
    source = _ir(nets=[{"name": "VMID", "pins": _pins(("R1", "2"), ("R2", "1"))}])
    generated = _ir(nets=[{"name": "OTHER", "pins": _pins(("R1", "2"), ("R2", "1"))}])

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "failed"
    assert "NET_NAMES_MISMATCH" in {mismatch.code for mismatch in report.mismatches}


def test_named_single_terminal_net_does_not_match_unconnected_autogenerated_name() -> None:
    source = _ir(nets=[{"name": "SENSE", "pins": _pins(("R1", "1"))}])
    generated = _ir(nets=[{"name": "unconnected-(R1-Pad1)", "pins": _pins(("R1", "1"))}])

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "failed"
    assert "NET_NAMES_MISMATCH" in {mismatch.code for mismatch in report.mismatches}


def test_named_net_does_not_match_ambiguous_autogenerated_partitions() -> None:
    terminals = _pins(("R1", "2"), ("R2", "1"))
    source = _ir(nets=[{"name": "VMID", "pins": terminals}])
    generated = _ir(
        nets=[
            {"name": "Net-(R1-Pad2)", "pins": terminals},
            {"name": "Net-(R2-Pad1)", "pins": terminals},
        ]
    )

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "failed"
    assert "NET_NAMES_MISMATCH" in {mismatch.code for mismatch in report.mismatches}


def test_multiple_named_nets_reconcile_one_to_one_by_terminal_partition() -> None:
    source = _ir(
        refs=("R1", "R2", "R3"),
        nets=[
            {"name": "N1", "pins": _pins(("R1", "1"), ("R2", "1"))},
            {"name": "N2", "pins": _pins(("R2", "2"), ("R3", "1"))},
        ],
    )
    generated = _ir(
        refs=("R1", "R2", "R3"),
        nets=[
            {"name": "Net-(R1-Pad1)", "pins": _pins(("R1", "1"), ("R2", "1"))},
            {"name": "Net-(R2-Pad2)", "pins": _pins(("R2", "2"), ("R3", "1"))},
        ],
    )

    report = compare_circuit_ir_equivalence(source, generated)

    assert report.status == "passed"
    assert report.mismatches == ()
