"""Regression coverage for native KiCad netlist topology recovery."""

from __future__ import annotations

from pathlib import Path

import pytest

from kicad_pcb.adapters import FakeFs, FakeRunner, KicadCliAdapter, RunResult
from kicad_pcb.circuit_ir import CircuitIR, ComponentIR, NetIR, PinRefIR
from kicad_pcb.corpus.kicadsexpr import (
    KicadSexprNet,
    KicadSexprNetPin,
    parse_kicadsexpr_nets,
)
from kicad_pcb.electrical_equivalence import compare_circuit_ir_equivalence
from kicad_pcb.refinement.electrical import _supplement_xml_omitted_unnamed_nets

pytestmark = pytest.mark.unit


def _components() -> list[ComponentIR]:
    return [
        ComponentIR(ref="R1", symbol="TestLib:R", value="10k"),
        ComponentIR(ref="R2", symbol="TestLib:R", value="10k"),
    ]


def _expected_ir() -> CircuitIR:
    return CircuitIR(
        version="1",
        components=_components(),
        nets=[
            NetIR(name="VCC", pins=[PinRefIR(ref="R1", pin="1")]),
            NetIR(
                name="VMID",
                pins=[PinRefIR(ref="R1", pin="2"), PinRefIR(ref="R2", pin="1")],
            ),
            NetIR(name="GND", pins=[PinRefIR(ref="R2", pin="2")]),
        ],
    )


def _xml_candidate_ir(*, midpoint_assigned: bool = False) -> CircuitIR:
    nets = [
        NetIR(name="VCC", pins=[PinRefIR(ref="R1", pin="1")]),
        NetIR(name="GND", pins=[PinRefIR(ref="R2", pin="2")]),
    ]
    if midpoint_assigned:
        nets.append(NetIR(name="WRONG", pins=[PinRefIR(ref="R1", pin="2")]))
    return CircuitIR(version="1", components=_components(), nets=nets)


def _midpoint_native_net(*, name: str = "Net-(R1-Pad2)") -> KicadSexprNet:
    return KicadSexprNet(
        code=2,
        name=name,
        pins=(KicadSexprNetPin(ref="R1", pin="2"), KicadSexprNetPin(ref="R2", pin="1")),
        autogenerated=name.startswith("Net-("),
    )


def test_parse_kicadsexpr_nets_preserves_unnamed_terminal_partition() -> None:
    content = """
    (export
      (version D)
      (nets
        (net (code 0) (name "") (node (ref R1) (pin 9)))
        (net (code 1) (name VCC)
          (node (ref R1) (pin 1) (pinfunction ~) (pintype passive)))
        (net (code 2) (name "")
          (node (ref R2) (pin 1))
          (node (ref R1) (pin 2)))))
    """

    nets = parse_kicadsexpr_nets(content)

    assert len(nets) == 2
    assert nets[0] == KicadSexprNet(
        code=1,
        name="VCC",
        pins=(KicadSexprNetPin(ref="R1", pin="1"),),
        autogenerated=False,
    )
    assert nets[1].name == "Net-(R1-Pad2)"
    assert nets[1].autogenerated is True
    assert nets[1].pins == (
        KicadSexprNetPin(ref="R1", pin="2"),
        KicadSexprNetPin(ref="R2", pin="1"),
    )


def test_adapter_can_export_native_kicadsexpr_netlist() -> None:
    sch = Path("/proj/test.kicad_sch")
    output = Path("/proj/test.net")
    native_content = "(export (version D) (nets))"
    runner = FakeRunner({"sch export": RunResult(0, "", "")})
    fs = FakeFs(files={str(output): native_content})
    adapter = KicadCliAdapter(kicad_cli="kicad-cli", runner=runner, fs=fs)

    result, content = adapter.export_netlist(sch, output, netlist_format="kicadsexpr")

    assert result.ok
    assert content == native_content
    assert runner.calls[-1] == [
        "kicad-cli",
        "sch",
        "export",
        "netlist",
        "--output",
        str(output),
        "--format",
        "kicadsexpr",
        str(sch),
    ]


def test_exact_native_unnamed_partition_recovers_xml_omission() -> None:
    expected = _expected_ir()
    candidate = _xml_candidate_ir()

    supplemented = _supplement_xml_omitted_unnamed_nets(
        expected_ir=expected,
        candidate_ir=candidate,
        native_nets=(_midpoint_native_net(),),
        helper_refs=(),
    )

    report = compare_circuit_ir_equivalence(expected, supplemented)
    assert report.status == "passed"
    assert {net.name for net in supplemented.nets} == {"VCC", "GND", "Net-(R1-Pad2)"}


def test_explicit_wrong_native_name_is_not_used_for_recovery() -> None:
    supplemented = _supplement_xml_omitted_unnamed_nets(
        expected_ir=_expected_ir(),
        candidate_ir=_xml_candidate_ir(),
        native_nets=(_midpoint_native_net(name="WRONG"),),
        helper_refs=(),
    )

    assert {net.name for net in supplemented.nets} == {"VCC", "GND"}


def test_xml_assigned_terminal_blocks_native_recovery() -> None:
    supplemented = _supplement_xml_omitted_unnamed_nets(
        expected_ir=_expected_ir(),
        candidate_ir=_xml_candidate_ir(midpoint_assigned=True),
        native_nets=(_midpoint_native_net(),),
        helper_refs=(),
    )

    assert {net.name for net in supplemented.nets} == {"VCC", "GND", "WRONG"}


def test_ambiguous_native_partition_blocks_recovery() -> None:
    first = _midpoint_native_net()
    second = KicadSexprNet(
        code=3,
        name="Net-(R2-Pad1)",
        pins=first.pins,
        autogenerated=True,
    )

    supplemented = _supplement_xml_omitted_unnamed_nets(
        expected_ir=_expected_ir(),
        candidate_ir=_xml_candidate_ir(),
        native_nets=(first, second),
        helper_refs=(),
    )

    assert {net.name for net in supplemented.nets} == {"VCC", "GND"}
